name: Horizon-Test-Plugin
version: ${version}
main: dev.gideonwhite1029.testplugin.TestPlugin
description: Horizon Test Plugin
author: GideonWhite1029
api-version: ${apiversion}
load: STARTUP
#bootstrapper: dev.gideonwhite1029.testplugin.TestPluginBootstrap
#loader: dev.gideonwhite1029.testplugin.TestPluginLoader
defaultPerm: FALSE
permissions:
dependencies:
