name: Build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6.2.0
        with:
          gradle-version: 9.4.1
          add-job-summary: never
          cache-read-only: false
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Configure Git
        run: git config --global user.email "action@github.com" && git config --global user.name "Github Action"
      - name: Apply patches
        run: ./gradlew applyAllPatches --no-daemon --stacktrace
      - name: Build
        run: ./gradlew createPaperclipJar --no-daemon --stacktrace
      - name: Rebuild on Failure
        if: ${{ failure() }}
        run: |
          ./gradlew clean cleanCache --refresh-dependencies
          ./gradlew applyAllPatches --no-daemon --stacktrace 
          ./gradlew createPaperclipJar --no-daemon --stacktrace
