name: Horizon CI

on:
  push:
    branches: [ "ver/26.1.2" ]
  repository_dispatch:
    types: [upstream-updated]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.ref || github.ref }}
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: 9.4.1
          add-job-summary: never
          cache-read-only: false
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Setup Git Config
        run: git config --global user.email "action@github.com" && git config --global user.name "Github Action"
      - name: Apply Patches
        run: gradle applyAllPatches
      - name: Create Jar
        run: gradle createMojmapPaperclipJar
      - name: Get Release Info
        run: sh scripts/ReleaseInfo.sh
      - name: Upload Artifact
        uses: "actions/upload-artifact@v7"
        with:
          name: "${{ env.project_id_b }} CI Artifacts"
          path: "horizon-server/build/libs/*.jar"
      - name: Create Release
        if: "!contains(github.event.commits[0].message, '[release skip]')"
        uses: ncipollo/release-action@v1.21.0
        with:
          tag: ${{ env.tag }}
          name: ${{ env.project_id_b }} ${{ env.mcversion }} - ${{ env.commit_id }}
          body: |
            📦Version: `${{ env.mcversion }}` | Commit ${{ env.commit_id }} [![download](https://img.shields.io/github/downloads/GideonWhite1029/${{ env.project_id_b }}/${{ env.tag }}/total?color=0&style=flat-square)](https://github.com/GideonWhite1029/${{ env.project_id_b }}/download/${{ env.tag }}/${{ env.jar }})
            This release is automatically compiled by GitHub Actions
            ### Commit Message
            ${{ env.commit_msg }}
          artifacts: |
            ${{ env.jar_dir }}
            horizon-server/build/libs/${{ env.project_id }}-${{ env.mcversion }}-bundler.jar
          generateReleaseNotes: true
          prerelease: ${{ env.pre }}
          makeLatest: ${{ env.make_latest }}
          token: "${{ secrets.GITHUB_TOKEN }}"
